[2021-08-12 10:57:19,951] {taskinstance.py:886} INFO - Dependencies not met for <TaskInstance: parallel_dag_02.processing_tasks 2021-08-11T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state which is not a valid state for execution. The task must be cleared in order to be run.
[2021-08-12 10:57:19,951] {local_task_job.py:96} INFO - Task is not able to be run
